#%RAML 1.0 Library

uses:
  tra: ../traits/traits.lib.raml
  typ: ../schemas/base-types.lib.raml

resourceTypes:
  read-only-collection:
    get:
      responses:
        200:
          headers:
            Last-Modified:
              description: The last date at which the collection was modified
          body:
            application/json:
              type: typ.Get<<resourcePathName | !uppercamelcase>>Response
  collection:
    type: read-only-collection
    post:
      body:
        type: typ.Post<<resourcePathName | !uppercamelcase>>Request
      responses:
        201:
          description: Created!
          headers:
            Location:
              description: URI of new resource
              type: string
              required: true
  read-only-member:
    get:
      responses:
        200:
          headers:
            ETag:
              description:
  member:
    type: read-only-member
    put?:
      body:
        type: typ.Put<<resourcePathName | !uppercamelcase>>Request
      responses:
        204:
          description: Modified
    patch?:
      body:
        type: typ.Patch<<resourcePathName | !uppercamelcase>>Request
    delete?:
      responses:
        204:
          description: Delete
