#%RAML 1.0 Library

uses:
  typ: base-types.lib.raml

types:
  Address:
    type: typ.Resource
    properties:
      id: string
      line1: string
      line2: string
      postCode: number
      city: string
      state: string
  Customer:
    type: typ.Resource
    properties:
      firstName: string
      lastName: string
      phone: string
      addresses: Address[]
  GetCustomerResponse:
    type: typ.GetResourceResponse
    properties:
      data?: Customer
  GetCustomersResponse:
    type: typ.GetCollectionResponse
    properties:
      data?: Customer[]
  PostCustomerRequest:
    type: Customer
